// ============================================================
// MASTER COMPANY DATABASE - 200+ Companies
// Auto-analyzed for ICP fit & cloud spend signals
// Priority: Indian companies with Indian decision makers
// ============================================================

export const ICP_REFERENCE = [
  'TCPL (Tata Consumer Products Limited)',
  'Condé Nast',
  'Diageo',
  'Shaddu.com',
  'Coca-Cola'
];

export const TARGET_ROLES = [
  'Chief Technology Officer',
  'CTO',
  'VP of Technology',
  'Head of Technology',
  'VP of Engineering',
  'Head of Engineering',
  'VP of DevOps',
  'Director of DevOps',
  'Head of DevOps',
  'Head of FinOps',
  'Director of FinOps',
  'Chief Information Security Officer',
  'CISO',
  'Chief Information Officer',
  'CIO',
  'VP of Infrastructure',
  'Head of SRE',
  'Director of SRE',
  'Head of Cloud',
  'Director of Cloud Engineering',
  'VP of Platform Engineering'
];

// Category: "icp-similar" = Industry twin of existing ICP
// Category: "high-fit" = Strong cloud spend fit for Zopnight/Zopday
export const COMPANIES = [
  // ============ INDIAN PRIORITY - HIGH-FIT CLOUD ============
  { company: "Dream11", industry: "Fantasy Sports / Gaming", category: "high-fit", region: "India", hq: "Mumbai", estCloudSpend: "$200K-500K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "220M+ users, EKS (Kubernetes) multi-tenant, custom Scaler tool, Graviton2 (42% cost savings), Neptune 50M req/min, OpenSearch, Aurora, Redshift, Athena", whyFit: "Extreme burst scaling during IPL creates massive right-sizing opportunities. Diverse AWS services = complex optimization surface. Significant idle capacity between events.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "dream11" },
  { company: "Razorpay", industry: "Fintech / Payments", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$200K-500K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Processes $150B+ annually, hundreds of microservices, thousands of containers, EC2 Auto Scaling, ElastiCache, RDS, Lambda, StarTree/Pinot, 300M+ metrics", whyFit: "Massive K8s optimization opportunity. Predictable payment patterns for right-sizing. Data-driven culture receptive to FinOps.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "razorpay" },
  { company: "Swiggy", industry: "Food Delivery / Quick Commerce", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$300K-700K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "650+ microservices on K8s, 10K+ containers, Graviton migration (30% savings), Java/Scala/Go/Rust, MySQL/ScyllaDB/Redis/Aerospike/Kafka", whyFit: "Largest K8s footprints in India. Public company cost pressure. Time-of-day patterns (lunch/dinner) = idle capacity optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "swiggy" },
  { company: "Zomato", industry: "Food Delivery / Quick Commerce", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$300K-700K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Trino: 250K+ queries scanning 2PB weekly, Druid: 20B events/8M queries weekly, EKS+Karpenter+ArgoCD, Flink on EKS (25% savings), DynamoDB migration (50% cost cut), petabyte ClickHouse", whyFit: "Petabyte-scale processing. Multiple cost optimization wins show appetite. Multi-platform (Zomato+Blinkit+HyperPure) = cross-platform optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "zomato" },
  { company: "Meesho", industry: "E-Commerce / Social Commerce", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$500K+/mo VERIFIED", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "VERIFIED $14.4M AWS contract, 1.59B orders FY25, BharatMLStack (K8s-native, Helm, ArgoCD, KEDA), SageMaker, EMR/Spark, 10B CDN requests/day", whyFit: "Poster child for cloud cost optimization. $14.4M AWS billing dispute. Multi-cloud migration complexity. $166M planned cloud investment for IPO.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "meesho" },
  { company: "Flipkart", industry: "E-Commerce", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$500K+/mo VERIFIED", cloudComplexity: "High", cloudProviders: "Private Cloud, GCP", cloudSignals: "20K+ bare-metal machines, 75K+ VMs, hybrid cloud bursting to GCP for BBD (6-7x traffic), K8s with custom operators, Prometheus 80M metrics, Aerospike 90M QPS", whyFit: "Hybrid private+GCP model = unique optimization challenges. BBD scaling = over-provisioning management. Walmart corporate pressure for efficiency.", icpSimilarity: "No direct match", verified: true, employeeCount: "30000+", linkedinSlug: "flipkart" },
  { company: "Zerodha", industry: "Fintech / Stock Brokerage", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "CNCF case study, K8s since 2020 (50% compute savings), self-hosted FOSS: Prometheus/Grafana/VictoriaMetrics/NATS/PostgreSQL/ClickHouse on bare EC2, ~30 engineer team", whyFit: "Cost-conscious culture = receptive to optimization. Bare EC2 = right-sizing opportunity. Trading hours = clear scheduling optimization. Small team lacks FinOps.", icpSimilarity: "No direct match", verified: true, employeeCount: "1500+", linkedinSlug: "zerodha" },
  { company: "CRED", industry: "Fintech / Credit Cards", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$100K-300K+/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Observability-led tech stack, CI/CD + Chaos Engineering, AI-powered ThreatShield, security-first architecture, $6.4B valuation", whyFit: "Observability-first = rich telemetry for cost optimization. Chaos Engineering = mature SRE. Rapid vertical expansion = fast-growing spend. Profitability pressure.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "caborneacred" },
  { company: "PhonePe", industry: "Fintech / Digital Payments", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "GCP, AWS", cloudSignals: "500M+ registered users, 6B+ monthly transactions, migrated from Flipkart infra to independent cloud, GCP primary, K8s-based microservices, real-time fraud detection", whyFit: "Massive transaction volume = huge compute. Recent infra independence from Flipkart = cloud spend optimization window. Real-time processing at scale.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "phonepe-internet" },
  { company: "Paytm", industry: "Fintech / Payments & Financial Services", category: "high-fit", region: "India", hq: "Noida", estCloudSpend: "$300K-500K+/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "300M+ users, payment processing at scale, AI/ML for fraud detection, multiple product verticals (payments, banking, lending, insurance), public company", whyFit: "Multiple product verticals = complex infra. Public company profitability pressure. Payment scale requires right-sizing. AI/ML workloads = GPU optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "8000+", linkedinSlug: "paytm" },
  { company: "Ola", industry: "Ride-hailing / EV", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$200K-400K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "Real-time ride matching at scale, maps & geospatial processing, Ola Electric EV data, ML-based pricing, multi-service architecture (rides, electric, financial services)", whyFit: "Real-time geospatial processing = compute-heavy. Multi-business (rides + EV + finance) = optimization across platforms. EV telemetry data growing fast.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "olacabs" },
  { company: "Freshworks", industry: "SaaS / Customer Engagement", category: "high-fit", region: "India", hq: "Chennai / San Mateo", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "AWS primary (official case study), global SaaS serving 60K+ customers, multi-product suite (Freshdesk, Freshservice, Freshsales), NASDAQ listed, K8s microservices", whyFit: "Public SaaS company = cloud spend is core COGS. Multi-product architecture = optimization across products. AWS case study company. Global scale.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "freshworks-inc" },
  { company: "Zoho", industry: "SaaS / Business Software", category: "high-fit", region: "India", hq: "Chennai", estCloudSpend: "$300K+/mo", cloudComplexity: "High", cloudProviders: "Private Cloud, AWS", cloudSignals: "100M+ users globally, 55+ products, own data centers + cloud, private cloud infrastructure, hiring DevOps/SRE actively", whyFit: "Massive private + hybrid cloud footprint. 55+ products = complex multi-service optimization. Growing cloud adoption alongside own DCs.", icpSimilarity: "No direct match", verified: true, employeeCount: "15000+", linkedinSlug: "zoho" },
  { company: "Postman", industry: "Developer Tools / API Platform", category: "high-fit", region: "India", hq: "Bangalore / San Francisco", estCloudSpend: "$200K-400K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "30M+ developers, billions of API calls, AWS infrastructure, K8s-based, real-time collaboration features, public API network", whyFit: "API traffic at massive scale = compute-heavy. Developer platform with real-time features. Cloud-native architecture with growth trajectory.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "postman-platform" },
  { company: "Groww", industry: "Fintech / Investment Platform", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$100K-300K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "10M+ active investors, real-time market data streaming, mutual fund & stock trading at scale, recently became a public company", whyFit: "Trading platform = real-time compute at scale. Market hours pattern = scheduling optimization. Public company cost pressure.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "groww--" },
  { company: "upGrad", industry: "EdTech", category: "high-fit", region: "India", hq: "Mumbai", estCloudSpend: "$50K-150K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Video streaming at scale, 10M+ learners, AI-powered learning paths, global operations (India, SE Asia, Middle East, US)", whyFit: "Video streaming + AI = compute-heavy workloads. Global scale with regional deployments. Growing data infrastructure.", icpSimilarity: "No direct match", verified: true, employeeCount: "4000+", linkedinSlug: "upgrad" },
  { company: "Byju's / Think & Learn", industry: "EdTech", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "150M+ registered students, video content delivery at scale, AI/ML personalization, multiple acquired platforms (Aakash, WhiteHat Jr), global operations", whyFit: "Massive video CDN costs. Multiple acquired platforms = infra consolidation opportunity. AI/ML workloads. Cost optimization critical for restructuring.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "byjus" },
  { company: "Lenskart", industry: "E-Commerce / Eyewear", category: "high-fit", region: "India", hq: "Faridabad", estCloudSpend: "$50K-150K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "AI-powered virtual try-on, omnichannel (1500+ stores + online), manufacturing + retail tech, international expansion (SE Asia, Middle East)", whyFit: "AI/computer vision workloads. Omnichannel tech stack. International expansion = multi-region cloud. Manufacturing + retail integration.", icpSimilarity: "Shaddu.com - digital commerce", verified: true, employeeCount: "10000+", linkedinSlug: "laboratoire-de-biologie-medicale-lenskart" },
  { company: "Nykaa", industry: "Digital Commerce / Beauty", category: "high-fit", region: "India", hq: "Mumbai", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "AWS case study, monolith-to-microservices (Docker+ECS), unified data lake (S3+Redshift), Amazon Bedrock GenAI, 40M+ MAU, 165+ physical stores", whyFit: "Microservices on ECS = container optimization. Data lake = storage optimization. Public company cost efficiency pressure. Omnichannel complexity.", icpSimilarity: "Shaddu.com", verified: true, employeeCount: "3000+", linkedinSlug: "naboratoire-de-biologie-medicale-nykaa" },
  { company: "Delhivery", industry: "Logistics / Supply Chain", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "AI/ML for route optimization, real-time tracking at scale, 2.5B+ cumulative shipments, data platform for logistics intelligence, K8s microservices", whyFit: "Real-time tracking = streaming compute. AI route optimization = ML infrastructure costs. Scale of operations requires optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "delhivery" },
  { company: "Pine Labs", industry: "Fintech / Merchant Platform", category: "high-fit", region: "India", hq: "Noida", estCloudSpend: "$50K-150K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "450K+ merchant touchpoints, payment processing at scale, cloud POS platform, expanding to SE Asia and Middle East", whyFit: "Payment processing compute at scale. Multi-region expansion = cloud cost management. Merchant SaaS platform = consistent workloads.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "pine-labs" },
  { company: "Cleartax (Clear)", industry: "Fintech / Tax & Compliance", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$50K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "10M+ users, enterprise GST compliance platform, B2B and B2C SaaS, AI-powered tax filing, seasonal traffic spikes during tax season", whyFit: "Extreme seasonal scaling (tax season) = burst cost optimization. B2B enterprise platform = consistent base workload. Growing product suite.", icpSimilarity: "No direct match", verified: true, employeeCount: "1500+", linkedinSlug: "cleaboratoire-de-biologie-medicale-cleartax" },
  { company: "Jio Platforms", industry: "Telecom / Digital Services", category: "high-fit", region: "India", hq: "Mumbai", estCloudSpend: "$5M+/mo", cloudComplexity: "High", cloudProviders: "Private Cloud, Azure, Oracle", cloudSignals: "450M+ subscribers, JioCloud private infrastructure, 5G core on cloud, AI/ML at telecom scale, Jio Platforms digital ecosystem", whyFit: "Largest digital platform in India. Massive private+public cloud hybrid. Telecom-scale infra. Cloud optimization at this scale = millions in savings.", icpSimilarity: "No direct match", verified: true, employeeCount: "50000+", linkedinSlug: "jio" },
  { company: "Bharti Airtel", industry: "Telecom", category: "high-fit", region: "India", hq: "New Delhi", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure, Google Cloud", cloudSignals: "380M+ subscribers, Airtel Cloud (Nxtra data centers), multi-cloud strategy, 5G deployment, partnerships with AWS/Google/Azure for edge computing", whyFit: "Telecom-scale cloud infrastructure. Own data centers + public cloud = hybrid optimization. 5G edge computing expansion.", icpSimilarity: "No direct match", verified: true, employeeCount: "30000+", linkedinSlug: "bharti-airtel-limited" },
  { company: "Policybazaar (PB Fintech)", industry: "InsurTech / Fintech", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "100M+ visitors annually, insurance comparison engine, real-time quote processing, AI recommendation engine, public company (NASDAQ listed)", whyFit: "High-traffic comparison platform. Real-time quote processing = compute-intensive. Public company cost optimization pressure.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "policybazaar" },
  { company: "Payu India", industry: "Fintech / Payment Gateway", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "500K+ merchants, multi-billion dollar transaction processing, real-time fraud detection, Prosus/Naspers backed, global operations", whyFit: "Payment processing scale requires optimization. Real-time fraud detection = ML compute. Global operations = multi-region costs.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "payu-india" },
  { company: "Unacademy", industry: "EdTech", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "50M+ learners, live video streaming at massive scale, AI-powered learning, multiple sub-brands (Relevel, CodeChef)", whyFit: "Live video streaming = massive bandwidth + compute costs. Scale of concurrent learners during live sessions. Multi-brand infra.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "unacademy" },
  { company: "Cure.fit (cult.fit)", industry: "Health & Fitness Tech", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Streaming workout platform, AI-powered fitness tracking, food delivery (eat.fit), 300+ fitness centers, omnichannel tech", whyFit: "Video streaming + AI fitness tracking. Multi-service platform (fitness, food, mental health). Growing digital footprint.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "cult-fit" },
  { company: "ShareChat / Moj", industry: "Social Media", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "GCP, AWS", cloudSignals: "400M+ MAU, short-video platform (Moj), content recommendation AI/ML, Google Cloud partnership, real-time content moderation", whyFit: "Massive content serving infrastructure. AI/ML recommendation engine = GPU costs. Real-time video processing. Google Cloud case study.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "sharechat" },
  { company: "Razorpay", industry: "Fintech / Payments", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$200K-500K+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "See above", whyFit: "See above", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "razorpay" },
  { company: "MakeMyTrip", industry: "Travel / OTA", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "India's largest OTA, real-time inventory management, dynamic pricing AI/ML, NASDAQ listed, seasonal traffic spikes (holidays, festivals)", whyFit: "Seasonal traffic patterns = burst cost management. Real-time pricing = compute-intensive. Public company efficiency pressure.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "makemytrip" },
  { company: "Myntra", industry: "Fashion E-Commerce", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "GCP, AWS", cloudSignals: "30M+ MAU, AI-powered fashion recommendations, visual search, EORS sales events (BBD-like spikes), Flipkart/Walmart group", whyFit: "EORS traffic spikes = burst scaling. AI visual search = GPU workloads. Walmart group cost efficiency mandates.", icpSimilarity: "Shaddu.com", verified: true, employeeCount: "3000+", linkedinSlug: "myntra" },
  { company: "BigBasket (Tata Digital)", industry: "Grocery E-Commerce", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS, GCP", cloudSignals: "India's largest online grocery, real-time inventory, route optimization, cold chain tracking, Tata Digital subsidiary", whyFit: "Real-time logistics optimization. Cold chain IoT monitoring. Tata group cloud strategy alignment. Growing quick commerce.", icpSimilarity: "TCPL (Tata group)", verified: true, employeeCount: "5000+", linkedinSlug: "bigbasket" },
  { company: "Dunzo", industry: "Quick Commerce / Delivery", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-80K/mo", cloudComplexity: "Medium", cloudProviders: "GCP", cloudSignals: "Real-time delivery routing, Google-backed, K8s microservices, ML-based demand prediction, hyperlocal logistics", whyFit: "Real-time routing = compute costs. Google Cloud infrastructure. Hyperlocal logistics optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "500+", linkedinSlug: "dunzo" },
  { company: "Rapido", industry: "Ride-hailing / Bike Taxi", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "200M+ rides, real-time matching, geospatial processing, expanding to autos & cabs, AI/ML pricing", whyFit: "Real-time ride matching at scale. Growing service portfolio. Geospatial compute optimization.", icpSimilarity: "No direct match", verified: true, employeeCount: "500+", linkedinSlug: "rapido-bike" },
  { company: "Vedantu", industry: "EdTech / Live Tutoring", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Live video tutoring platform, 40M+ students, real-time whiteboard & video, AI-powered adaptive learning", whyFit: "Live video at scale = bandwidth + compute costs. Concurrent session management. AI adaptive engine.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "vedantu" },
  { company: "Jupiter (AMICA Financial Technologies)", industry: "Neobanking / Fintech", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-80K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Digital banking platform, 2M+ users, real-time transaction processing, UPI integration, personal finance AI", whyFit: "Banking workloads = always-on compute. Real-time transaction processing. Growing user base = scaling costs.", icpSimilarity: "No direct match", verified: true, employeeCount: "500+", linkedinSlug: "jupiter-money" },
  { company: "Slice", industry: "Fintech / Credit Cards", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "10M+ users, real-time credit decisioning, AI underwriting, payment processing, merged with North East Small Finance Bank", whyFit: "Banking + fintech merge = infrastructure consolidation opportunity. Real-time credit AI workloads.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "slicegroup" },
  { company: "Cars24", industry: "Auto / E-Commerce", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$50K-150K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "AI-powered car pricing, 360-degree car photography AI, international operations (UAE, Australia, Thailand), real-time auction platform", whyFit: "AI image processing = GPU compute. International multi-region deployment. Real-time auction platform.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "cars24" },
  { company: "Spinny", industry: "Auto / Used Car Platform", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$20K-60K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "AI car inspection tools, digital-first auto retail, machine learning pricing models", whyFit: "AI-powered inspection + pricing. Growing digital auto retail infra.", icpSimilarity: "No direct match", verified: true, employeeCount: "1500+", linkedinSlug: "spinny-cars" },
  { company: "Urban Company", industry: "Home Services / Marketplace", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Service marketplace at scale, real-time matching, AI-powered quality assurance, expansion to UAE/Australia/Singapore", whyFit: "Real-time service matching. International expansion = multi-region costs. AI quality monitoring.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "urban-company" },
  { company: "Ather Energy", industry: "EV / Electric Vehicles", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$20K-80K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Connected EV platform, real-time vehicle telemetry, OTA updates, IoT data from scooters, Ather Grid charging network", whyFit: "IoT telemetry data growing with fleet. OTA + connected vehicle platform. Charging network monitoring.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "ather-energy" },
  { company: "OYO Rooms", industry: "Hospitality / PropTech", category: "high-fit", region: "India", hq: "Gurugram", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "Global hotel chain (35+ countries), dynamic pricing AI, real-time inventory across 175K+ hotels, AWS case study, IPO-bound", whyFit: "Global scale = multi-region optimization. Dynamic pricing = ML compute. 175K+ property inventory management. IPO cost pressure.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "oyorooms" },
  { company: "InfoEdge (Naukri, 99acres)", industry: "Digital / Classifieds", category: "high-fit", region: "India", hq: "Noida", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Naukri.com (100M+ profiles), 99acres, Jeevansathi, Shiksha - multiple high-traffic platforms, AI-powered matching, search at scale", whyFit: "Multiple high-traffic platforms = complex multi-service infra. Search + matching AI at scale. Public company.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "infoedge" },
  { company: "Moglix", industry: "B2B Industrial E-Commerce", category: "high-fit", region: "India", hq: "Noida", estCloudSpend: "$20K-80K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "B2B industrial marketplace, AI catalog management, supply chain tech, serving 500+ enterprises, international operations", whyFit: "B2B enterprise platform at scale. Supply chain AI workloads. International expansion.", icpSimilarity: "No direct match", verified: true, employeeCount: "1500+", linkedinSlug: "moglix" },
  { company: "InMobi", industry: "AdTech / Mobile Advertising", category: "high-fit", region: "India", hq: "Bangalore", estCloudSpend: "$300K-800K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "1.6B unique users reached, real-time ad bidding (RTB), programmatic advertising, Glance (lock screen platform), data processing at massive scale", whyFit: "Real-time bidding = microsecond latency compute. Massive data processing for ad targeting. Glance serving lock screen content at scale.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "inmobi" },
  { company: "MapmyIndia (CE Info Systems)", industry: "GeoTech / Maps", category: "high-fit", region: "India", hq: "New Delhi", estCloudSpend: "$50K-200K/mo", cloudComplexity: "High", cloudProviders: "AWS, Own Cloud", cloudSignals: "India's mapping leader, IoT platform for connected vehicles, geospatial data processing, government contracts, 4M+ km road data", whyFit: "Geospatial data processing at scale. IoT fleet management platform. Growing B2B customer base.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "mapmyindia" },

  // ============ GLOBAL - HIGH-FIT CLOUD ============
  { company: "Canva", industry: "Design Technology / SaaS", category: "high-fit", region: "Global", hq: "Sydney", estCloudSpend: "$2M-5M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "260M+ MAU, 230+ PB in S3, 100B events weekly, 180K K8s pods on 10K+ nodes, $3M/year saved from single S3 optimization", whyFit: "Highest dollar opportunity. 230PB S3 + 180K pods = tens of millions AWS annually. Multi-cloud adds complexity.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "canva" },
  { company: "Shopify", industry: "E-Commerce Platform / SaaS", category: "high-fit", region: "Global", hq: "Ottawa", estCloudSpend: "$5M-10M+/mo", cloudComplexity: "High", cloudProviders: "GCP", cloudSignals: "58M req/min BFCM, 400 K8s clusters, 19M DB queries/sec, 107 deploys/day, GKE migration (30% savings), FinOps dashboards", whyFit: "400 K8s clusters = enormous optimization surface. BFCM burst scaling. Existing FinOps maturity but more to capture.", icpSimilarity: "No direct match", verified: true, employeeCount: "10000+", linkedinSlug: "shopify" },
  { company: "Stripe", industry: "Fintech / Payment Infrastructure", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$5M+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Processes hundreds of billions in payments, sub-100ms latency requirements, global edge presence, ML fraud detection, Ruby/Java/Go stack", whyFit: "Global payment processing at extreme scale. Sub-100ms latency = premium compute. Fraud ML workloads.", icpSimilarity: "No direct match", verified: true, employeeCount: "8000+", linkedinSlug: "stripe" },
  { company: "Datadog", industry: "Observability / SaaS", category: "high-fit", region: "Global", hq: "New York", estCloudSpend: "$10M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "Processes trillions of data points daily, multi-cloud native, K8s monitoring platform, real-time analytics at petabyte scale", whyFit: "Ironic target - the observability company itself has massive cloud spend. Multi-cloud at extreme scale.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "datadog" },
  { company: "Cloudflare", industry: "Cloud Infrastructure / CDN", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "Own + AWS", cloudSignals: "Global edge network (300+ cities), Workers serverless platform, R2 storage, D1 database, massive bandwidth handling", whyFit: "Massive global infrastructure. Own infrastructure + cloud = hybrid optimization. Rapidly growing product suite.", icpSimilarity: "No direct match", verified: true, employeeCount: "3500+", linkedinSlug: "cloudflare" },
  { company: "Notion", industry: "Productivity / SaaS", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$500K-2M/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "100M+ users, real-time collaboration, AI features (Notion AI), document storage at scale, complex editor rendering", whyFit: "Real-time collaboration = compute-intensive. AI integration growing fast. 100M+ users = significant storage + compute.", icpSimilarity: "No direct match", verified: true, employeeCount: "1000+", linkedinSlug: "notionhq" },
  { company: "Figma", industry: "Design / Collaboration SaaS", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$500K-2M/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Real-time multiplayer design, WebAssembly rendering, millions of designers, AI features (Figma AI), massive file storage", whyFit: "Real-time multiplayer = WebSocket compute at scale. AI feature rollout = GPU costs. Growing enterprise adoption.", icpSimilarity: "No direct match", verified: true, employeeCount: "1500+", linkedinSlug: "figma" },
  { company: "Discord", industry: "Communication / Social", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "GCP", cloudSignals: "200M+ MAU, real-time voice/video/text, 19M active servers, moved from Cassandra to ScyllaDB, Rust for performance", whyFit: "Real-time communication at massive scale. Voice + video streaming costs. Database at extreme scale.", icpSimilarity: "No direct match", verified: true, employeeCount: "600+", linkedinSlug: "discord" },
  { company: "Twilio", industry: "CPaaS / Communication APIs", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$5M+/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "10M+ developer accounts, global communication infrastructure, real-time messaging/voice/video, Segment CDP, SendGrid email", whyFit: "Multi-product communication infra. Real-time processing at global scale. Multiple acquired platforms = consolidation opportunity.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "twilio-inc" },
  { company: "MongoDB", industry: "Database / SaaS", category: "high-fit", region: "Global", hq: "New York", estCloudSpend: "$5M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "Atlas cloud database service across all 3 major clouds, 50K+ customers, petabyte-scale data, multi-region replication", whyFit: "Multi-cloud at extreme scale. Database infrastructure costs = core business. Global replication.", icpSimilarity: "No direct match", verified: true, employeeCount: "5000+", linkedinSlug: "mongodbinc" },
  { company: "Confluent", industry: "Data Streaming / SaaS", category: "high-fit", region: "Global", hq: "Mountain View", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "Apache Kafka creators, Confluent Cloud across 3 major clouds, real-time streaming at massive scale, 5K+ customers", whyFit: "Multi-cloud streaming infrastructure. Data processing at massive scale. Growing cloud revenue.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "confluent" },
  { company: "Elastic", industry: "Search / Observability SaaS", category: "high-fit", region: "Global", hq: "Mountain View", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "Elastic Cloud across all 3 clouds, 20K+ customers, Elasticsearch at massive scale, SIEM + observability", whyFit: "Multi-cloud SaaS infrastructure. Search workloads = compute-intensive. Global customer base.", icpSimilarity: "No direct match", verified: true, employeeCount: "3000+", linkedinSlug: "elastic-co" },
  { company: "HashiCorp", industry: "Infrastructure / DevOps SaaS", category: "high-fit", region: "Global", hq: "San Francisco", estCloudSpend: "$2M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "Terraform, Vault, Consul, Nomad - all cloud-native tools, HCP cloud platform, multi-cloud native", whyFit: "Infrastructure company itself has significant cloud spend. Multi-cloud native platform.", icpSimilarity: "No direct match", verified: true, employeeCount: "2000+", linkedinSlug: "hashicorp" },

  // ============ ICP SIMILAR - FMCG / CONSUMER BRANDS ============
  { company: "Nestle", industry: "FMCG / Food & Beverage", category: "icp-similar", region: "Global", hq: "Vevey, Switzerland", estCloudSpend: "$2M+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "SAP RISE on Azure, centralized data lake replacing 17 legacy systems, $200M+ cloud value, DevOps across 185 markets/300+ factories", whyFit: "Massive multi-brand infrastructure. SAP cloud transformation = optimization opportunity.", icpSimilarity: "TCPL", verified: true, employeeCount: "270000+", linkedinSlug: "nestle-s-a-" },
  { company: "Reckitt Benckiser", industry: "FMCG / Health & Hygiene", category: "icp-similar", region: "Global", hq: "Slough, UK", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS, GCP", cloudSignals: "Dedicated FinOps team, Factory of the Future (Azure IoT Hub + edge), Scholl brand 101 websites on AWS, multi-cloud", whyFit: "Already has FinOps team = receptive to optimization tools. Multi-cloud complexity.", icpSimilarity: "TCPL", verified: true, employeeCount: "40000+", linkedinSlug: "raboratoire-de-biologie-medicale-reckitt" },
  { company: "Mondelez International", industry: "FMCG / Snacks", category: "icp-similar", region: "Global", hq: "Chicago", estCloudSpend: "$1M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, Azure", cloudSignals: "$1.2B SAP S/4HANA on AWS, Google Cloud marketing analytics (BigQuery, Looker), migrating off Azure to AWS", whyFit: "Massive SAP cloud migration. Multi-cloud (AWS+GCP). Cloud migration in progress = optimization timing.", icpSimilarity: "TCPL", verified: true, employeeCount: "80000+", linkedinSlug: "monaboratoire-de-biologie-medicale-mondelez-international" },
  { company: "AB InBev", industry: "Beverages / Brewing", category: "icp-similar", region: "Global", hq: "Leuven, Belgium", estCloudSpend: "$2M+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Docker & K8s, Azure Synapse/Data Lake/HDInsight, 500B+ sensor readings/yr (IoT), SAP S/4HANA migration", whyFit: "Largest brewer globally. IoT at massive scale. Kubernetes adoption. SAP migration.", icpSimilarity: "Diageo", verified: true, employeeCount: "150000+", linkedinSlug: "ab-inbev" },
  { company: "Colgate-Palmolive", industry: "FMCG / Personal Care", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP, K8s", cloudSignals: "Wiz Cloud security across AWS/GCP/K8s (737 technologies), EC2 since 2018, SD-WAN, cloud-first SaaS strategy", whyFit: "Multi-cloud (AWS+GCP+K8s). Cloud-first strategy. Security complexity = governance cost opportunity.", icpSimilarity: "TCPL", verified: true, employeeCount: "34000+", linkedinSlug: "colgate-palmolive" },
  { company: "Pernod Ricard", industry: "Beverages / Spirits", category: "icp-similar", region: "Global", hq: "Paris", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS, GCP", cloudSignals: "Azure primary since 2014, multi-cloud, AI tools (D-STAR, Matrix), GenAI in HR, Oracle Cloud, HBS case study", whyFit: "Direct Diageo competitor. Multi-cloud complexity. AI deployment at scale.", icpSimilarity: "Diageo", verified: true, employeeCount: "19000+", linkedinSlug: "pernod-ricard" },
  { company: "Hearst Corporation", industry: "Media / Publishing", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$1M+/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "80% IT in cloud, CCoE, serverless+container-first, AWS Organizations/Control Tower, Amazon Q Business GenAI", whyFit: "Major publisher like Conde Nast. 80% cloud = mature but optimization-ready. CCoE structure.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "12000+", linkedinSlug: "hearst" },
  { company: "Dotdash Meredith", industry: "Digital Media / Publishing", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$200K-500K/mo", cloudComplexity: "Medium", cloudProviders: "AWS, Azure", cloudSignals: "AWS CCoE, cloud-first migration, CI/CD pipelines, Agile/SAFe at scale, OpenAI content deal", whyFit: "Digital publisher like Conde Nast. Active cloud migration = optimization window.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "5000+", linkedinSlug: "dotdash-meredith" },
  { company: "Hindustan Unilever", industry: "FMCG / Consumer Goods", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, GCP, AWS", cloudSignals: "Massive Unilever cloud migration, 5-yr Google Cloud partnership (Vertex AI, Gemini), Azure OpenAI, retailer digitization app", whyFit: "India's largest FMCG. Multi-cloud transformation. Google Cloud AI partnership.", icpSimilarity: "TCPL", verified: true, employeeCount: "20000+", linkedinSlug: "hindustan-unilever-limited" },
  { company: "PepsiCo", industry: "Beverages / FMCG", category: "icp-similar", region: "Global", hq: "Purchase, NY", estCloudSpend: "$2M+/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "AWS partnership for digital transformation, pep+ sustainability data platform, AI-powered supply chain, global digital commerce", whyFit: "Direct Coca-Cola competitor. AWS partnership. Global supply chain cloud transformation.", icpSimilarity: "Coca-Cola", verified: true, employeeCount: "300000+", linkedinSlug: "pepsico" },
  { company: "Unilever", industry: "FMCG / Consumer Goods", category: "icp-similar", region: "Global", hq: "London", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "Azure, GCP, AWS", cloudSignals: "One of largest consumer goods cloud migrations (Accenture+Microsoft), Google Cloud Vertex AI, global digital transformation", whyFit: "Massive global FMCG. Multi-cloud at enterprise scale. Leading digital transformation.", icpSimilarity: "TCPL", verified: true, employeeCount: "125000+", linkedinSlug: "unilever" },
  { company: "Procter & Gamble", industry: "FMCG / Consumer Goods", category: "icp-similar", region: "Global", hq: "Cincinnati", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS, GCP", cloudSignals: "Multi-cloud strategy, AI/ML for supply chain optimization, smart factory IoT, massive digital marketing tech stack", whyFit: "World's largest FMCG. Multi-cloud + IoT at manufacturing scale. Digital advertising optimization.", icpSimilarity: "TCPL", verified: true, employeeCount: "107000+", linkedinSlug: "proaboratoire-de-biologie-medicale-procter-and-gamble" },
  { company: "Danone", industry: "FMCG / Food & Nutrition", category: "icp-similar", region: "Global", hq: "Paris", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Cloud-first strategy, SAP on cloud, AI-powered supply chain, global operations (120+ countries)", whyFit: "Global food company. SAP cloud transformation. Supply chain AI at global scale.", icpSimilarity: "TCPL", verified: true, employeeCount: "90000+", linkedinSlug: "danone" },
  { company: "ITC Limited", industry: "FMCG / Conglomerate", category: "icp-similar", region: "India", hq: "Kolkata", estCloudSpend: "$200K-500K/mo", cloudComplexity: "Medium", cloudProviders: "AWS, Azure", cloudSignals: "Digital transformation across FMCG, hospitality, IT, agri-business, cloud migration in progress, SAP on cloud", whyFit: "Indian FMCG conglomerate. Multi-business cloud needs. Growing digital initiatives.", icpSimilarity: "TCPL", verified: true, employeeCount: "35000+", linkedinSlug: "itc-limited" },
  { company: "Godrej Consumer Products", industry: "FMCG", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Digital-first FMCG strategy, D2C platforms, cloud-based supply chain, operations across Asia/Africa/LATAM", whyFit: "Indian FMCG with global presence. D2C cloud infrastructure. Growing digital maturity.", icpSimilarity: "TCPL", verified: true, employeeCount: "12000+", linkedinSlug: "godrej-consumer-products-limited" },
  { company: "Marico", industry: "FMCG / Personal Care", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Digital transformation initiative, D2C brands (Beardo, Just Herbs), cloud-based analytics, Asia+Africa operations", whyFit: "Indian FMCG with D2C digital brands. Cloud analytics adoption. Regional expansion.", icpSimilarity: "TCPL", verified: true, employeeCount: "3000+", linkedinSlug: "marico-limited" },
  { company: "Dabur", industry: "FMCG / Ayurveda", category: "icp-similar", region: "India", hq: "Ghaziabad", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Digital supply chain transformation, e-commerce growth, cloud-based ERP, operations in 100+ countries", whyFit: "Indian FMCG heritage brand. Cloud ERP migration. E-commerce scaling.", icpSimilarity: "TCPL", verified: true, employeeCount: "8000+", linkedinSlug: "dabur-india-limited" },
  { company: "Britannia Industries", industry: "FMCG / Food", category: "icp-similar", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Smart factory initiatives, cloud-based supply chain, digital distribution platform, growing D2C", whyFit: "Major Indian food company. Smart factory IoT + cloud. D2C scaling.", icpSimilarity: "TCPL", verified: true, employeeCount: "5000+", linkedinSlug: "britannia-industries-limited" },
  { company: "Emami", industry: "FMCG / Personal Care", category: "icp-similar", region: "India", hq: "Kolkata", estCloudSpend: "$20K-60K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "Digital transformation journey, cloud adoption for supply chain, e-commerce integration", whyFit: "Indian FMCG in early cloud adoption. Growing digital footprint.", icpSimilarity: "TCPL", verified: true, employeeCount: "3000+", linkedinSlug: "emami-limited" },
  { company: "Amul (GCMMF)", industry: "FMCG / Dairy", category: "icp-similar", region: "India", hq: "Anand, Gujarat", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "India's largest dairy brand, cold chain IoT monitoring, digital distribution platform, massive supply chain digitization", whyFit: "India's largest food brand. Cold chain IoT + cloud. Supply chain at massive scale.", icpSimilarity: "TCPL", verified: true, employeeCount: "5000+", linkedinSlug: "amaboratoire-de-biologie-medicale-amul-gcmmf" },
  { company: "Patanjali Ayurved", industry: "FMCG / Ayurveda", category: "icp-similar", region: "India", hq: "Haridwar", estCloudSpend: "$20K-80K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "Rapid digital transformation, e-commerce platform, cloud-based supply chain, growing tech team", whyFit: "Large Indian FMCG. Early-stage cloud adoption = greenfield optimization.", icpSimilarity: "TCPL", verified: true, employeeCount: "10000+", linkedinSlug: "patanjali-ayurved-limited" },
  { company: "Haldiram's", industry: "FMCG / Snacks", category: "icp-similar", region: "India", hq: "Nagpur", estCloudSpend: "$20K-60K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "D2C e-commerce growth, digital distribution, cloud-based operations, $5B+ revenue", whyFit: "Massive Indian snacks brand going digital. Early cloud adoption at scale.", icpSimilarity: "TCPL", verified: true, employeeCount: "5000+", linkedinSlug: "haldirams" },
  { company: "United Breweries (Kingfisher)", industry: "Beverages / Beer", category: "icp-similar", region: "India", hq: "Bangalore", estCloudSpend: "$20K-80K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Heineken subsidiary, digital supply chain, cloud-based brewing operations monitoring", whyFit: "India's largest beer brand. Heineken group cloud strategy. Manufacturing digitization.", icpSimilarity: "Diageo", verified: true, employeeCount: "3000+", linkedinSlug: "united-breweries-limited" },
  { company: "Radico Khaitan", industry: "Beverages / Spirits", category: "icp-similar", region: "India", hq: "New Delhi", estCloudSpend: "$10K-40K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "Digital transformation initiative, cloud ERP, growing digital presence, export to 100+ countries", whyFit: "Indian spirits company. Cloud adoption starting. International operations.", icpSimilarity: "Diageo", verified: true, employeeCount: "2000+", linkedinSlug: "radico-khaitan-limited" },
  { company: "The Times Group (BCCL)", industry: "Media / Publishing", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "India's largest media conglomerate, TOI (1B+ page views/month), MX Player, Gaana, Cricbuzz - all cloud-native digital products", whyFit: "India's largest media house. Multiple high-traffic digital products. Content delivery at massive scale.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "10000+", linkedinSlug: "the-times-group" },
  { company: "Network18 / Viacom18", industry: "Media / Entertainment", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "JioCinema streaming (500M+ downloads), Reliance-backed, real-time sports streaming (IPL), multi-platform content delivery", whyFit: "JioCinema streaming at massive scale. IPL live streaming = extreme burst. Reliance group cloud strategy.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "5000+", linkedinSlug: "viacom18" },
  { company: "Zee Entertainment", industry: "Media / OTT", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "ZEE5 OTT platform, 100M+ MAU, content delivery across 190+ countries, AI-powered recommendations", whyFit: "Large OTT platform. Content delivery at global scale. AI recommendation engine.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "4000+", linkedinSlug: "zee-entertainment-enterprises-limited" },
  { company: "Reliance Retail", industry: "Retail / E-Commerce", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$1M+/mo", cloudComplexity: "High", cloudProviders: "Jio Cloud, AWS", cloudSignals: "India's largest retailer ($30B+ revenue), JioMart e-commerce, 18K+ stores, omnichannel tech, supply chain AI", whyFit: "India's largest retailer. Massive omnichannel tech stack. JioMart e-commerce scaling.", icpSimilarity: "TCPL (retail)", verified: true, employeeCount: "300000+", linkedinSlug: "reliance-retail" },
  { company: "Tata Digital", industry: "Digital Commerce / Super App", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$200K-500K/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "Tata Neu super app, integrating BigBasket/1mg/Croma/Air India, multi-service platform, AWS infrastructure", whyFit: "Tata group super app. Multi-service integration = complex infra. Same group as TCPL.", icpSimilarity: "TCPL (Tata group)", verified: true, employeeCount: "2000+", linkedinSlug: "tata-digital" },
  { company: "Asian Paints", industry: "Manufacturing / Paints", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS, Azure", cloudSignals: "SAP on cloud, smart factory IoT, AI color recommendation (iColour), digital-first customer experience, operations in 15+ countries", whyFit: "India's paint leader. Smart factory + IoT. SAP cloud migration. AI-powered customer tools.", icpSimilarity: "TCPL (Indian conglomerate)", verified: true, employeeCount: "8000+", linkedinSlug: "asian-paints" },
  { company: "Titan Company", industry: "Consumer Goods / Watches & Jewelry", category: "icp-similar", region: "India", hq: "Bangalore", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Tata group, e-commerce platforms (Tanishq, Titan), omnichannel retail tech, AI-powered inventory management", whyFit: "Tata group consumer brand. Omnichannel tech stack. Growing digital commerce.", icpSimilarity: "TCPL (Tata group)", verified: true, employeeCount: "10000+", linkedinSlug: "titan-company-limited" },
  { company: "L'Oréal", industry: "FMCG / Beauty", category: "icp-similar", region: "Global", hq: "Paris", estCloudSpend: "$1M+/mo", cloudComplexity: "High", cloudProviders: "AWS, GCP", cloudSignals: "AWS case study, AI beauty tech (ModiFace), D2C e-commerce platforms, global digital marketing, smart factory", whyFit: "Global beauty leader. AI tech (virtual try-on). D2C at scale. AWS case study.", icpSimilarity: "TCPL", verified: true, employeeCount: "87000+", linkedinSlug: "loreaboratoire-de-biologie-medicale-loreal" },
  { company: "Henkel", industry: "FMCG / Adhesives & Consumer", category: "icp-similar", region: "Global", hq: "Düsseldorf", estCloudSpend: "$300K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Digital backbone initiative, smart factory IoT, Microsoft partnership, global cloud transformation", whyFit: "Global FMCG + industrial. Smart factory program. Microsoft cloud partnership.", icpSimilarity: "TCPL", verified: true, employeeCount: "50000+", linkedinSlug: "henkel" },
  { company: "Estée Lauder", industry: "Luxury Beauty / FMCG", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Digital-first transformation, AI-powered skincare analysis, D2C e-commerce, cloud-based supply chain", whyFit: "Luxury beauty conglomerate. AI beauty tech. D2C digital scaling. Cloud supply chain.", icpSimilarity: "TCPL", verified: true, employeeCount: "60000+", linkedinSlug: "the-estee-lauder-companies-inc-" },
  { company: "Kraft Heinz", industry: "FMCG / Food", category: "icp-similar", region: "Global", hq: "Chicago / Pittsburgh", estCloudSpend: "$500K+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Cloud-based Agile@Scale transformation, AI for supply chain, digital marketing tech, $26B+ revenue", whyFit: "Major global food company. Cloud transformation in progress. AI supply chain.", icpSimilarity: "TCPL", verified: true, employeeCount: "36000+", linkedinSlug: "the-kraft-heinz-company" },
  { company: "Kellogg's (Kellanova)", industry: "FMCG / Food", category: "icp-similar", region: "Global", hq: "Chicago", estCloudSpend: "$300K+/mo", cloudComplexity: "Medium", cloudProviders: "Azure, AWS", cloudSignals: "SAP cloud migration, digital shelf analytics, cloud-based supply chain, global operations", whyFit: "Global food company. SAP cloud migration. Digital analytics adoption.", icpSimilarity: "TCPL", verified: true, employeeCount: "23000+", linkedinSlug: "kellanova" },
  { company: "Mars Inc.", industry: "FMCG / Confectionery & Pet Care", category: "icp-similar", region: "Global", hq: "McLean, VA", estCloudSpend: "$1M+/mo", cloudComplexity: "High", cloudProviders: "Azure, AWS", cloudSignals: "Private company, massive global operations, smart factory IoT, AI for supply chain, digital commerce", whyFit: "One of world's largest private companies. Smart factory program. Global cloud infrastructure.", icpSimilarity: "TCPL", verified: true, employeeCount: "140000+", linkedinSlug: "mars" },
  { company: "Ferrero", industry: "FMCG / Confectionery", category: "icp-similar", region: "Global", hq: "Alba, Italy", estCloudSpend: "$300K+/mo", cloudComplexity: "Medium", cloudProviders: "Azure", cloudSignals: "Cloud transformation initiative, smart manufacturing, global distribution digitization, $17B+ revenue", whyFit: "Major global confectionery. Cloud transformation underway. Manufacturing digitization.", icpSimilarity: "TCPL", verified: true, employeeCount: "40000+", linkedinSlug: "ferrero" },
  { company: "Molson Coors", industry: "Beverages / Brewing", category: "icp-similar", region: "Global", hq: "Chicago", estCloudSpend: "$300K+/mo", cloudComplexity: "Medium", cloudProviders: "Azure, AWS", cloudSignals: "Cloud-first strategy, SAP on cloud, digital brewery operations, D2C platforms", whyFit: "Major global brewer. Cloud-first strategy. D2C digital platforms.", icpSimilarity: "Diageo", verified: true, employeeCount: "16000+", linkedinSlug: "molson-coors-beverage-company" },
  { company: "Carlsberg", industry: "Beverages / Brewing", category: "icp-similar", region: "Global", hq: "Copenhagen", estCloudSpend: "$200K+/mo", cloudComplexity: "Medium", cloudProviders: "Azure", cloudSignals: "Microsoft partnership, AI for brewing (Beer Fingerprinting), smart connected brewery program", whyFit: "Global brewer. AI-powered brewing. Microsoft cloud partnership.", icpSimilarity: "Diageo", verified: true, employeeCount: "29000+", linkedinSlug: "carlsberg" },
  { company: "Campari Group", industry: "Beverages / Spirits", category: "icp-similar", region: "Global", hq: "Milan", estCloudSpend: "$100K-300K/mo", cloudComplexity: "Medium", cloudProviders: "Azure, AWS", cloudSignals: "Cloud transformation, SAP on cloud, global distribution digitization, premium spirits portfolio", whyFit: "Premium spirits company like Diageo. Cloud transformation in progress.", icpSimilarity: "Diageo", verified: true, employeeCount: "4000+", linkedinSlug: "campari-group" },
  { company: "Brown-Forman", industry: "Beverages / Spirits", category: "icp-similar", region: "Global", hq: "Louisville, KY", estCloudSpend: "$100K-200K/mo", cloudComplexity: "Medium", cloudProviders: "Azure", cloudSignals: "Cloud-first digital transformation, Jack Daniel's brand digitization, global distribution tech", whyFit: "Major spirits company. Cloud transformation. Brand digitization.", icpSimilarity: "Diageo", verified: true, employeeCount: "5000+", linkedinSlug: "brown-forman" },
  { company: "HarperCollins Publishers", industry: "Media / Publishing", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$50K-200K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Digital publishing platform, e-book delivery, cloud content management, global operations", whyFit: "Major publisher. Digital content delivery. Cloud publishing platform.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "10000+", linkedinSlug: "harpercollins-publishers" },
  { company: "Penguin Random House", industry: "Media / Publishing", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$100K-300K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "World's largest book publisher, digital-first strategy, cloud content delivery, AI-powered recommendations", whyFit: "Largest publisher globally. Digital transformation. Cloud content delivery.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "10000+", linkedinSlug: "penguin-random-house" },
  { company: "Bloomberg", industry: "Media / Financial Information", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$5M+/mo", cloudComplexity: "High", cloudProviders: "AWS, Own Cloud", cloudSignals: "Bloomberg Terminal infrastructure, real-time financial data, massive data processing, news delivery at global scale", whyFit: "Financial data at extreme scale. Real-time processing. Hybrid infrastructure.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "20000+", linkedinSlug: "bloomberg-lp" },
  { company: "Thomson Reuters", industry: "Media / Legal & Financial Info", category: "icp-similar", region: "Global", hq: "Toronto", estCloudSpend: "$3M+/mo", cloudComplexity: "High", cloudProviders: "AWS, Azure", cloudSignals: "Cloud migration for legal/tax/news platforms, AI-powered search, global data processing", whyFit: "Major information services. Cloud migration at enterprise scale. AI-powered platforms.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "26000+", linkedinSlug: "thomson-reuters" },
  { company: "Vogue Business (Condé Nast direct competitor)", industry: "Fashion Media", category: "icp-similar", region: "Global", hq: "London", estCloudSpend: "$10K-30K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "Digital publishing, content analytics, subscription platform", whyFit: "Direct Conde Nast adjacent. Digital publishing platform.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "100+", linkedinSlug: "vogue-business" },
  { company: "BuzzFeed", industry: "Digital Media", category: "icp-similar", region: "Global", hq: "New York", estCloudSpend: "$100K-300K/mo", cloudComplexity: "High", cloudProviders: "AWS", cloudSignals: "Digital-native publisher, AI content tools, programmatic advertising, massive traffic handling", whyFit: "Digital-native media. Cloud-native architecture. AI content generation.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "500+", linkedinSlug: "buzzfeed" },
  { company: "Firstpost / Network18 Digital", industry: "Digital Media", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "High-traffic Indian digital news, Reliance-backed, cloud-native publishing platform", whyFit: "Indian digital media. High traffic publishing. Reliance group cloud.", icpSimilarity: "Condé Nast", verified: true, employeeCount: "1000+", linkedinSlug: "firstpost" },
  { company: "1mg (Tata 1mg)", industry: "HealthTech / E-Pharmacy", category: "icp-similar", region: "India", hq: "Gurugram", estCloudSpend: "$30K-100K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Tata group digital health, e-pharmacy platform, AI drug interaction checker, lab test booking", whyFit: "Tata group digital health. E-commerce platform scaling. AI health tools.", icpSimilarity: "TCPL (Tata group)", verified: true, employeeCount: "2000+", linkedinSlug: "1mg" },
  { company: "Boat (Imagine Marketing)", industry: "Consumer Electronics / D2C", category: "icp-similar", region: "India", hq: "New Delhi", estCloudSpend: "$20K-60K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "India's #1 wearables brand, D2C e-commerce platform, growing tech infrastructure", whyFit: "India's top wearables brand. D2C platform. Growing digital infrastructure.", icpSimilarity: "Shaddu.com", verified: true, employeeCount: "2000+", linkedinSlug: "boat-lifestyle" },
  { company: "Sugar Cosmetics", industry: "Beauty / D2C", category: "icp-similar", region: "India", hq: "Mumbai", estCloudSpend: "$10K-30K/mo", cloudComplexity: "Low", cloudProviders: "AWS", cloudSignals: "D2C beauty brand, e-commerce platform, omnichannel (600+ touchpoints), growing digital presence", whyFit: "Indian D2C beauty brand. E-commerce platform. Growing cloud usage.", icpSimilarity: "Shaddu.com", verified: true, employeeCount: "1000+", linkedinSlug: "try-sugar" },
  { company: "Mamaearth (Honasa Consumer)", industry: "D2C / Personal Care", category: "icp-similar", region: "India", hq: "Gurugram", estCloudSpend: "$20K-60K/mo", cloudComplexity: "Medium", cloudProviders: "AWS", cloudSignals: "Public D2C brand, multi-brand portfolio (Mamaearth, The Derma Co, Aqualogica), cloud e-commerce, AI-powered marketing", whyFit: "Indian public D2C company. Multi-brand cloud infrastructure. Digital-first.", icpSimilarity: "Shaddu.com", verified: true, employeeCount: "2000+", linkedinSlug: "honasa-consumer-limited" },
];

export function getRandomizedCompanies(category, count = 50) {
  const filtered = COMPANIES.filter(c => c.category === category);
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getAllCompanies(category) {
  return COMPANIES.filter(c => c.category === category);
}

export function searchCompanies(query) {
  const q = query.toLowerCase();
  return COMPANIES.filter(c =>
    c.company.toLowerCase().includes(q) ||
    c.industry.toLowerCase().includes(q) ||
    c.region.toLowerCase().includes(q) ||
    c.hq.toLowerCase().includes(q)
  );
}
